// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9u3AmkLTGufk_lqa8-AmVbJaLHW_GuY',
    appId: '1:671572102202:web:0500397be3edc264017903',
    messagingSenderId: '671572102202',
    projectId: 'pantry-panda-v2',
    authDomain: 'pantry-panda-v2.firebaseapp.com',
    storageBucket: 'pantry-panda-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq65FUsft-cMpyquBAgFUNA31nAxgtOMw',
    appId: '1:671572102202:android:540d36737e93a371017903',
    messagingSenderId: '671572102202',
    projectId: 'pantry-panda-v2',
    storageBucket: 'pantry-panda-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUw7jHG-Vqn91LFycqcq3PxGxB85QCrIc',
    appId: '1:671572102202:ios:ba6507ab58f7f75b017903',
    messagingSenderId: '671572102202',
    projectId: 'pantry-panda-v2',
    storageBucket: 'pantry-panda-v2.firebasestorage.app',
    iosClientId: '671572102202-mgb6hcaf2pmfj3dhu6ovd2v14an5f0fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryPandaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUw7jHG-Vqn91LFycqcq3PxGxB85QCrIc',
    appId: '1:671572102202:ios:ba6507ab58f7f75b017903',
    messagingSenderId: '671572102202',
    projectId: 'pantry-panda-v2',
    storageBucket: 'pantry-panda-v2.firebasestorage.app',
    iosClientId: '671572102202-mgb6hcaf2pmfj3dhu6ovd2v14an5f0fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryPandaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa9u3AmkLTGufk_lqa8-AmVbJaLHW_GuY',
    appId: '1:671572102202:web:2ef2be4de3f49483017903',
    messagingSenderId: '671572102202',
    projectId: 'pantry-panda-v2',
    authDomain: 'pantry-panda-v2.firebaseapp.com',
    storageBucket: 'pantry-panda-v2.firebasestorage.app',
  );
}
